config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:index, :edit, :update, :create, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]

  get "/home/about" => "homes#about",as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image
  
  validates :name, length: { in: 2..20 }, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end 
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end 
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render "index"
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @books = @user.books
    @bookn = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
    @books = Book.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
      <table class='table'>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>

        <% @books.each do |book| %>
          <%= link_to user_path(@user.id) do %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image, size:"80x80" %>
              <% end %>
            </td>
            <td><%=link_to book.title, book_path(book.id)%></td>
            <td><%= book.body %></td>
            <td>
          <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book), method: :delete do %>
               <i class = "fas fa-heart"></i>
               <%= book.favorites.count %>
              <% end %>
           <% else %>
             <%= link_to book_favorites_path(book), method: :post do %>
              <i class = "fas fa-heart"></i>
              <%= book.favorites.count %> 
             <% end %>
           <% end %></td>
            </td>
            <td>
              <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">

      <div class="col-md-6 mx-auto">
        <h1>Editing Book</h1>
        
        <% if @book.errors.any? %>
          <%= @book.errors.count %> errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        
        <%= form_with model: @book do |f| %>
          <div class="form-label mb-3"> 
            <h6>Title</h6>
            <%= f.text_field :title, class: "form-control", style: "width:100", rows: "1" %>
          </div>
          <div class="form-label mb-3"> 
            <h6>Opinion</h6>
            <%= f.text_area :body, class: "form-control", style: "width:100", rows: "2" %>
          </div>
          <div class="button mb-3">
            <%= f.submit 'Update Book',class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show",book_path(@book.id)%> |
        <%= link_to "Back",books_path %>
      </div>

  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class= "row">

    <div class= "col-md-3">
      <h2>User info</h2>
      <table class='table'>
        <%= image_tag @user.get_profile_image %>
        <tr>
          <td><strong>name</strong></td>
          <td><strong><%= @user.name %></strong></td>
        </tr>
        <tr>
          <td><strong>introduction</strong></td>
          <td><strong><%= @user.introduction %></strong></td>
        </tr>
      </table>
      <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block mb-3 mt-5" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
      <div class="form-label mb-3"> 
        <h6>Title</h6>
        <%= f.text_field :title, class: "form-control", style: "width:100" %>
      </div>
      <div class="form-label mb-3"> 
        <h6>Opinion</h6>
        <%= f.text_area :body, class: "form-control", style: "width:100" %>
      </div>
        <%= f.submit 'Create Book',class: "btn btn-success" %>
      <% end %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class= "row">

    <div class= "col-md-3">
      <h2>User info</h2>
      <table class='table'>
        <%= image_tag @book.user.get_profile_image %>
        <tr>
          <td><strong>name</strong></td>
          <td><strong><%= @book.user.name %></strong></td>
        </tr>
        <tr>
          <td><strong>introduction</strong></td>
          <td><strong><%= @book.user.introduction %></strong></td>
        </tr>
      </table>
      <% if @book.user_id == current_user.id %>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block mb-3 mt-5" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
        <% else %>
          <%= link_to edit_user_path(@book.user.id), class: "btn btn-outline-secondary btn-block mb-3 mt-5" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
      <% end %>


      <h2>New book</h2>
      <%= form_with model: @bookn do |f| %>
        <h6>Title</h6>
        <%= f.text_field :title %>
        <h6>Opinion</h6>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book',class: "btn btn-success" %>
      <% end %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class='table'>
        <%= link_to user_path(@user.id) do %>
          <tr>
            <td> 
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image, size:"80x80" %>
              <nav>
                <%= @book.user.name %>
              </nav>
            <% end %>
            </td>
            <td><%=link_to @book.title %></td>
            <td><%= @book.body %></td>
            <td> 
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class = "fas fa-heart"></i>
                    <%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class = "fas fa-heart"></i>
                    <%= @book.favorites.count %> 
                <% end %>
              <% end %>
            </td>
            
            <td><%= link_to "#{@book.book_comments.count} コメント", book_path(@book.id) %></td>
            
            <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class:"btn btn-danger destroy(@book.id)", method: :delete, data: {confirm: "本当に消しますか？"} %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
          <% @book.book_comments.each do |book_comment| %>
            <%= image_tag book_comment.user.get_profile_image, size:"100x100" %>
            <%= book_comment.user.name %>
            <%= book_comment.comment %>
        
          <% if book_comment.user == current_user %>
          　<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment),  class:"btn btn-danger destroy(@book.id)", method: :delete %>
          <% end %>
          <% end %>
      <div>
        <%= form_with model: [@book,@book_comment] do |f| %>
          <%= f.text_area :comment, row: '5', placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto'>
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class="row">
    <div class='col-md-6 mx-auto'>
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1>
      <p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
    </div>
  </div>
  <div class="row">
    <div class='col-md-5 mb-3 mx-auto'>
        <a href="/users/sign_in" class="btn btn-info btn-block" role="button" >Log in</a>
    </div>
  </div>
  <div class="row">
    <div class='col-md-5 mx-auto'>
        <a href="/users/sign_up" class="btn btn-success btn-block" role="button" >Sign up</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm mb-3">
      <nav class="navbar navbar-expand-lg navbar-light bg-dark text-white">
        <div class="container">
          <strong><a class="navbar-brand p-1 text-white" href="/">Bookers</a></strong>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class:"text-white pr-4" do %>
                  <strong><i class="fas fa-home"></i><span> Home</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to "/users", class:"text-white pr-4" do %>
                  <strong><i class="fas fa-users"></i><span> Users</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to "/books", class:"text-white pr-4" do %>
                  <strong><i class="fas fa-book-open"></i><span> Books</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class:"text-white" do %>
                  <strong><i class="fas fa-sign-out-alt"></i><span> Log out</span></strong>
                <% end %>
              </li>

              <% else %>
              
              <li class="nav-item">
                <%= link_to root_path, class:"text-white pr-4" do %>
                  <strong><i class="fas fa-home"></i><span> Home</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to about_path, class:"text-white pr-4" do %>
                  <strong><i class="fas fa-link"></i><span> About</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_registration_path, class:"text-white pr-4" do %>
                  <strong><i class="fas fa-user-plus"></i><span> Sign up</span></strong>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path, class:"text-white" do %>
                  <strong><i class="fas fa-sign-in-alt"></i><span> Log in</span></strong>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
  <%= yield %>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">

          <p>CopyRight Infratop.inc</p>

        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/_info.html.erb
      <table class='table'>
        <%= image_tag @user.get_profile_image %>
        <tr>
          <td><strong>name</strong></td>
          <td><strong><%= @user.name %></strong></td>
        </tr>
        <tr>
          <td><strong>introduction</strong></td>
          <td><strong><%= @user.introduction %></strong></td>
        </tr>
      </table>
      
      <div class= "row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block mb-3 mt-5" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">

      <%= form_with model: @user, url: user_path(current_user.id) do |f| %>
        <h2>User info</h2>

        <% if @user.errors.any? %>
          <%= @user.errors.count %> error prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="form-label mb-3">
          <h6>Name</h6>
          <%= f.text_field :name, class: "form-control", style: "width:100", rows: "1" %>
        </div>
        <div class="form-label mb-3">
          <h6>Image</h6>
          <%= f.file_field :profile_image %>
        </div>
        <div class="form-label mb-3">
          <h6>Introduction</h6>
          <%= f.text_area :introduction, class: "form-control", style: "width:100", rows: "2" %>
        </div>
        <div class="button mb-3">
          <%= f.submit 'Update User',class: "btn btn-secondary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class= "row">
    
    <div class= "col-md-3">
      <h2>User info</h2>
     <%= render 'info', user: current_user %>
     
      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
        <h6>Title</h6>
        <%= f.text_field :title %>
        <h6>Opinion</h6>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book',class: "btn btn-success" %>
      <% end %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class='table'>
        <th>image</th>
        <th>name</th>
        <th></th>

        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size:"80x80" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container">
  <div class= "row">

    <div class= "col-md-3">
      <h2>User info</h2>
      <table class='table'>
        <%= image_tag @user.get_profile_image %>
        <tr>
          <td><strong>name</strong></td>
          <td><strong><%= @user.name %></strong></td>
        </tr>
        <tr>
          <td><strong>introduction</strong></td>
          <td><strong><%= @user.introduction %></strong></td>
        </tr>
      </table>
      <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block mb-3 mt-5" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2>New book</h2>
      <%= form_with model: @book do |f| %>
        <h6>Title</h6>
        <%= f.text_field :title %>
        <h6>Opinion</h6>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book',class: "btn btn-success" %>
      <% end %>
    </div>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>

  </div>
</div>